name: check-flake
run-name: "Check Flake"
on:
  push:
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '*.md'

jobs:
  check-flake:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@v31
        name: "Install Nix"
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        name: "Checkout repository"

      - run: nix flake check
        name: "Check Flake"
