name: check-flake
run-name: "Check Flake – ${{ github.event.head_commit.message }}"
on:
  push:
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '*.md'

jobs:
  check-flake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        name: "Checkout repository"

      - uses: ./.github/actions/nix-setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix flake check
        name: "Check Flake"
