name: update-sbom
run-name: "Update SBOM – ${{ github.event.workflow_run.head_commit.message }}"
on:
  workflow_run:
    workflows:
      - check-flake
    types:
      - completed
    branches:
      - main

jobs:
  update-sbom:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v7
        name: "Checkout repository"

      - uses: ./.github/actions/nix-setup
        name: "Setup Nix"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: >
          nix develop ${{ github.workspace }}#sbom -c --
          sbomnix ${{ github.workspace }}#nixosConfigurations.snowball.config.system.build.toplevel
        name: "Generate SBOM"

      - uses: advanced-security/spdx-dependency-submission-action@v0.2.0
        name: "Submit SBOM to GitHub"
        with:
          filePath: "${{ github.workspace }}"
